version: "3.1"
services:
    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: your_username
            RABBITMQ_DEFAULT_PASS: your_password
        ports:
            - 5672:5672
            - 15672:15672
